spring:
  profiles:
    active: EN,cat,test

di:
  username: YmlUser
  password: YmlPass
  jdbcurl: jdbc:mysql:123.456.789.001:3306/yml_db
### ==================================================================================================================